// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $add from "./routes/add.tsx";
import * as $buscarOne from "./routes/buscarOne.tsx";
import * as $eliminarsuper from "./routes/eliminarsuper.tsx";
import * as $getonesuper_name_ from "./routes/getonesuper/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $no from "./routes/no.tsx";
import * as $deleteSuper from "./islands/deleteSuper.tsx";
import * as $eliminar from "./islands/eliminar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/add.tsx": $add,
    "./routes/buscarOne.tsx": $buscarOne,
    "./routes/eliminarsuper.tsx": $eliminarsuper,
    "./routes/getonesuper/[name].tsx": $getonesuper_name_,
    "./routes/index.tsx": $index,
    "./routes/no.tsx": $no,
  },
  islands: {
    "./islands/deleteSuper.tsx": $deleteSuper,
    "./islands/eliminar.tsx": $eliminar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
